### ISSUE TITLE
Can you use this yet?

### ISSUE THREAD

**Issue by nikitavoloboev** [mandrigin/AlfredSwitchWindows#1]
And if so, how do you actually get the .workflow file to import?

Thank you for any help.

**Comment by mandrigin** [comment]
It's in development, but I use it now. I use a heavily patched "Windows Switcher" workflow from Emanuele Munafò (https://www.alfredforum.com/topic/9326-a-simple-windows-switcher/).

I can send you the .workflow file to your email :) I don't want to share half-done project here yet.

PS: I can't really switch Safari tabs, yet. It only can open the Safari window containing specific tab.

**Comment by nikitavoloboev** [comment]
Yeah, I would love to see the workflow if you can send it to me :)

**Comment by nikitavoloboev** [comment]
Also check this (https://gogs.deanishe.net/deanishe/alfred-safari-assistant)

**Comment by mandrigin** [comment]
Thank you!
Sent you the workflow.

I just wanted to make everything using native code (or keep Apple Script to the bare minimum), because the performance looks is much better.

**Comment by nikitavoloboev** [comment]
Is it normal that it gives no results?

Do I have to change anything?

**Comment by mandrigin** [comment]
Did you compile the application?

**Comment by nikitavoloboev** [comment]
I have the .workflow file, I just imported it.

**Comment by mandrigin** [comment]
Ah, you need to have the application too (and tweak the path to the app). I can send you a debug binary of it too. :)
As I told, it is heavily in-development project...

**Comment by nikitavoloboev** [comment]
Yeah I understand, I will wait then. :)

I was using this before (https://github.com/jnewland/alfred-open-windows) but it stopped working.

**Comment by mandrigin** [comment]
Sent you the binary (for macOS Sierra) and an updated .workflow

**Comment by mandrigin** [comment]
@nikitavoloboev https://github.com/mandrigin/AlfredSwitchWindows/releases/tag/v0.2-alpha — packed a pre-release version. You just need the .workflow file now.

**Comment by nikitavoloboev** [comment]
This is really amazing. Would it be possible to extend this and add one more script filter to scope the search to only active windows of current application please?

Also for Safari tabs, look into this (https://gogs.deanishe.net/deanishe/alfred-safari-assistant), it is really well done. :)

**Comment by mandrigin** [comment]
Thanks you! I will take a look. I just made a 0.2.1 today, with slightly improved algorithms and visual representation of the Safari tabs and ignoring the menu bar items. 

Thanks for the ideas, I will consider them. :)
