### ISSUE TITLE
Tab not switching on Chrome

### ISSUE THREAD

**Issue by the-c0d3r** [mandrigin/AlfredSwitchWindows#12]
I downloaded the latest version, and tried to switch to a chrome (full-screened) window's tab. But it only bring me to the chrome window. It is essentially not switching the tab. 

And another thing I found is that it works on Safari (with or without the window being minimized), it will be great to maximize window if it is hidden/minimized after switching tab.

Great work 👍

**Comment by mandrigin** [comment]
The workflow currently doesn't support multiple spaces or full-screen windows. As it turned out it is much harder to make this support working stable than I expected.
Thanks for reporting!

**Comment by dyckia** [comment]
@mandrigin Hi mandrigin, I encountered the same issue as @the-c0d3r reported in the first paragraph,  which is that the switcher only brings me to the chrome window the tab is in, but not the tab itself. Any solutions or bug fixes?

**Comment by mandrigin** [comment]
@dyckia sometimes it just fails for me as well, but I didn't manage to debug it properly yet...
