### ISSUE TITLE
Dock displayed in the results

### ISSUE THREAD

**Issue by iiiaxdellai** [mandrigin/AlfredSwitchWindows#15]
The **dock** is displayed in the search results, but it's not something you would normally switch to imo 🤔 Do you reckon is worth to exclude it from the search scope?

<img width="600" alt="screen shot 2017-11-03 at 12 10 46" src="https://user-images.githubusercontent.com/19621044/32373219-1f51d6ba-c090-11e7-9d53-09e264f741af.png">

Nice workflow, I'm a big fun of it 👍

**Comment by mandrigin** [comment]
Hmm, I do filter it out and I can't reproduce it myself. I'll close the issue for now, but if it still happens, please reopen and tell a bit more about your OS configuration.
