### ISSUE TITLE
Can it support searching by application name?

### ISSUE THREAD

**Issue by Madd0g** [mandrigin/AlfredSwitchWindows#18]
For applications where the title doesn't contain the application name - e.g. chrome only contains the active tab title and not searchable by typing "chrome".

Thanks, great workflow!

**Comment by mandrigin** [comment]
@Madd0g I finally implemented that :) https://github.com/mandrigin/AlfredSwitchWindows/releases/tag/0.3.5

**Comment by gbstan** [comment]
Hi @mandrigin Any chance you can put the .alfredworkflow file on github too?

**Comment by mandrigin** [comment]
@gbstan I've added it to the release. Thanks for pointing that out!

**Comment by gbstan** [comment]
Thanks!
