### ISSUE TITLE
Chrome: only the foremost window works

### ISSUE THREAD

**Issue by jeremyhtml** [mandrigin/AlfredSwitchWindows#20]
For Chrome, the workflow only takes you to tabs on the foremost (last active) window and doesn't work on windows behind that one. However, it will show tabs from all windows in the search results. 

Chrome: 72.0
Alfred: 3.8
macOS: 10.14.3

This is an utterly fantastic idea for a workflow and I can't wait to see where it goes.

**Comment by azerbe** [comment]
Can confirm.
