### ISSUE TITLE
How to show all the open Windows

### ISSUE THREAD

**Issue by mikhailtugushev** [mandrigin/AlfredSwitchWindows#30]
Hi! The default workflow does not show the total list of all open window until you type the word. How to fix it?

**Comment by pelemarse** [comment]
Hack: After w char enter two space

**Comment by mandrigin** [comment]
> Hack: After w char enter two space
You are right, @pelemarse, thanks!
I think it is a good solution for now.
Otherwise, I'll have to significantly complicate the workflow itself.
