### ISSUE TITLE
EXC_BAD_INSTRUCTION on SwiftUI Project

### ISSUE THREAD

**Issue by johnnypi6** [mandrigin/AlfredSwitchWindows#35]
Hi, Many thanks for your ongoing support.

I called search(query:, onlyTabs:) function on the SwiftUI Mac project. But when this function is called, the app is crashed with EXC_BAD_INSTRUCTION error.

![image](https://user-images.githubusercontent.com/44872075/80535176-01515b80-8966-11ea-963c-47f92c7e82bf.png)

![image](https://user-images.githubusercontent.com/44872075/80535316-352c8100-8966-11ea-96ed-1229d29823a1.png)

![image](https://user-images.githubusercontent.com/44872075/80535429-61e09880-8966-11ea-8f0d-fb690124ef2d.png)

It seems that there is a duplicated release of the same instance in the function BrowserEntity.performSelectorByName.

Would you help me to fix this issue?

**Comment by mandrigin** [comment]
idk, maybe this stackoverflow answer will help: https://stackoverflow.com/questions/50774391/swift-4-getting-thread-1-exc-bad-access-error-with-avfoundation

because I have this line `guard let retainedValue = selectorResult?.takeRetainedValue() else {`

**Comment by johnnypi6** [comment]
Thank you for your kind help! I resolved the issue.
