### ISSUE TITLE
Packal is telling me to downgrade to 0.2.3

### ISSUE THREAD

**Issue by matthew-groth** [mandrigin/AlfredSwitchWindows#6]
![image](https://cloud.githubusercontent.com/assets/12831489/23827743/a0a6aca8-0688-11e7-81ab-d9a8391ce419.png)

**Comment by mandrigin** [comment]
Hmm, that's weird, I see 0.2.4 in Packal now and I don't have any update messages from Packal updater.

**Comment by mandrigin** [comment]
http://www.packal.org/workflow/swift-window-switcher — 0.2.4 is there

**Comment by matthew-groth** [comment]
Hmm looks like [Packal updater is outdated](https://www.alfredforum.com/topic/4579-packal-updater/?page=4)

**Comment by mandrigin** [comment]
I'm closing this issue then. There is nothing I can do about the updated Packal :(
