### ISSUE TITLE
Can't switch to a Safari tab

### ISSUE THREAD

**Issue by freewizard** [mandrigin/AlfredSwitchWindows#7]
macOS 10.12.4
Can see all tabs, can switch to window, but failed to change the active tab 

```
Starting debug for 'Swift Window Switcher'

[2017-03-28 08:08:55][ERROR: action.applescript] {
    NSAppleScriptErrorAppName = Safari;
    NSAppleScriptErrorBriefMessage = "Can\U2019t get tab 1079 of window 1. Invalid index.";
    NSAppleScriptErrorMessage = "Safari got an error: Can\U2019t get tab 1079 of window 1. Invalid index.";
    NSAppleScriptErrorNumber = "-1719";
    NSAppleScriptErrorRange = "NSRange: {420, 11}";
}
```

**Comment by mandrigin** [comment]
How many tabs do you have?

**Comment by freewizard** [comment]
4

**Comment by mandrigin** [comment]
Can you open the workflow in terminal and run ./EnumWindows --search="Safari" and put the output here?

**Comment by freewizard** [comment]
<items><item uid="1" arg="Safari|||||311|||||Can't switch to a Safari tab · Issue #7 · mandrigin/AlfredSwitchWindows" autocomplete="Can't switch to a Safari tab · Issue #7 · mandrigin/AlfredSwitchWindows"><title>Can't switch to a Safari tab · Issue #7 · mandrigin/AlfredSwitchWindows</title><icon>/Applications/Safari.app/Contents/Resources/compass.icns</icon><subtitle>https://github.com/mandrigin/AlfredSwitchWindows/issues/7#issuecomment-290912385</subtitle></item><item uid="1" arg="Safari|||||311|||||Hacker News" autocomplete="Google"><title>Google</title><icon>/Applications/Safari.app/Contents/Resources/compass.icns</icon><subtitle>https://www.google.com/</subtitle></item><item uid="1" arg="Safari|||||567|||||Hacker News" autocomplete="Hacker News"><title>Hacker News</title><icon>/Applications/Safari.app/Contents/Resources/compass.icns</icon><subtitle>https://news.ycombinator.com/</subtitle></item></items>

**Comment by mandrigin** [comment]
Thanks! So it's, 1 window and 3 tabs, right? Tab numbers look like error codes, frankly. I will try to investigate.

**Comment by mandrigin** [comment]
@freewizard should be fixed in https://github.com/mandrigin/AlfredSwitchWindows/releases/tag/0.2.5-beta

Please, reopen if still happens after the upgrade.
